#!/bin/bash -ex

[ -d vendor ] && cd vendor && rm -rf $(ls | grep -v plugins | grep -v bundle) && cd ..

command -v bundle || gem install bundler --no-ri --no-rdoc
bundle install --deployment --without test development cucumber

git describe --tags > public/version

# packing bundler itself
gem unpack bundler --target=vendor/bundler/gem
cd vendor/bundler/gem
BUNDLER=$(ls)
cd $BUNDLER
git init
git add -A
gem build bundler.gemspec
BUNDLER_GEM=$(ls | grep .gem$)
mv $BUNDLER_GEM ../../$BUNDLER_GEM
cd ../..
rm -rf gem
cd ../..
